version: '3'

networks:
  stlc:
    driver: bridge
services:
  nginx2:
    image: nginx:alpine
    container_name: webserver2
    ports:
      - "8089:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php2
    networks:
      - stlc

  php2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php2
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
    ports:
    - "9000:9000"
    networks:
      - stlc